[package]
name = "ryan-bridges/roblox-sync-test"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
dataservice = "leifstout/dataservice@1.0.0"
promise = "evaera/promise@4.0.0"
networker = "leifstout/networker@0.3.1"
signal = "stravant/goodsignal@0.3.1"
vide = "centau/vide@0.4.1"
topbarplus = "1foreverhd/topbarplus@3.4.0"

[server-dependencies]
profileservice = "firebird702/profileservice@1.1.0"
