-- These volumes match the combat floors currently present in Studio.
-- Add or rebalance entries here without changing the grouped spawning algorithm.
-- Keep each CFrame on its floor surface and its X/Z extent inside that floor so zombies
-- spawn above the ground and cannot cross into an adjacent difficulty zone.
local GAME_FLOOR_CFRAME = CFrame.new(180.2383, 0, 0)
local GAME_FLOOR_SIZE = Vector2.new(300, 300)

local ZombieAreas = {
	{
		Id = "StartingArea",
		Progression = 0,
		-- The run must begin around GameSpawnPos; leaving this floor unconfigured prevents the
		-- occupied-area spawner from ever creating a first wave until the player walks away.
		CFrame = CFrame.new(244.668, 0, 0),
		Size = Vector2.new(171.14, 110.448),
		-- Spawn regions tune encounter progression, but early zombies may chase across the entire
		-- authored baseplate instead of stopping at an invisible region boundary.
		MovementCFrame = GAME_FLOOR_CFRAME,
		MovementSize = GAME_FLOOR_SIZE,
		HealthMultiplier = 0.5,
		MaxZombies = 24,
		SpawnInterval = 3,
		GroupSize = NumberRange.new(2, 4),
		GroupRadius = 10,
		MinPlayerDistance = 28,
		ZombieWeights = {
			{ Name = "Walker", Weight = 64 },
			{ Name = "Runner", Weight = 20 },
			{ Name = "Spitter", Weight = 7 },
			{ Name = "Leaper", Weight = 4 },
			{ Name = "Dodger", Weight = 3 },
			{ Name = "Frenzy", Weight = 2 },
		},
	},
	{
		Id = "Area1",
		Progression = 1,
		CFrame = CFrame.new(105.1682, 0, 0),
		Size = Vector2.new(107.8594, 110.448),
		MovementCFrame = GAME_FLOOR_CFRAME,
		MovementSize = GAME_FLOOR_SIZE,
		MaxZombies = 30,
		SpawnInterval = 3,
		GroupSize = NumberRange.new(2, 4),
		GroupRadius = 10,
		MinPlayerDistance = 28,
		ZombieWeights = {
			{ Name = "Walker", Weight = 58 },
			{ Name = "Runner", Weight = 20 },
			{ Name = "Spitter", Weight = 8 },
			{ Name = "Leaper", Weight = 5 },
			{ Name = "Dodger", Weight = 4 },
			{ Name = "Frenzy", Weight = 3 },
			{ Name = "Brute", Weight = 2 },
		},
	},
	{
		Id = "Area2",
		Progression = 2,
		CFrame = CFrame.new(-2.6912, 0, 0),
		Size = Vector2.new(107.8594, 110.448),
		MaxZombies = 55,
		SpawnInterval = 2.5,
		GroupSize = NumberRange.new(3, 6),
		GroupRadius = 12,
		MinPlayerDistance = 30,
		ZombieWeights = {
			{ Name = "Walker", Weight = 30 },
			{ Name = "Runner", Weight = 18 },
			{ Name = "Brute", Weight = 8 },
			{ Name = "Spitter", Weight = 7 },
			{ Name = "Charger", Weight = 6 },
			{ Name = "Leaper", Weight = 5 },
			{ Name = "Grabber", Weight = 5 },
			{ Name = "Splitter", Weight = 5 },
			{ Name = "Frenzy", Weight = 5 },
			{ Name = "Medic", Weight = 4 },
			{ Name = "Hardened", Weight = 4 },
			{ Name = "Dodger", Weight = 3 },
		},
	},
	{
		Id = "Area3",
		Progression = 3,
		CFrame = CFrame.new(-110.5506, 0, 0),
		Size = Vector2.new(107.8594, 110.448),
		MaxZombies = 85,
		SpawnInterval = 2,
		GroupSize = NumberRange.new(4, 8),
		GroupRadius = 14,
		MinPlayerDistance = 32,
		ZombieWeights = {
			{ Name = "Walker", Weight = 16 },
			{ Name = "Runner", Weight = 12 },
			{ Name = "Brute", Weight = 8 },
			{ Name = "Spitter", Weight = 6 },
			{ Name = "Charger", Weight = 7 },
			{ Name = "Screamer", Weight = 3 },
			{ Name = "Tank", Weight = 2 },
			{ Name = "Leaper", Weight = 5 },
			{ Name = "Shielder", Weight = 6 },
			{ Name = "Bomber", Weight = 5 },
			{ Name = "Grabber", Weight = 5 },
			{ Name = "Summoner", Weight = 3 },
			{ Name = "Splitter", Weight = 5 },
			{ Name = "Burrower", Weight = 4 },
			{ Name = "Frenzy", Weight = 5 },
			{ Name = "Medic", Weight = 3 },
			{ Name = "Hardened", Weight = 3 },
			{ Name = "Dodger", Weight = 5 },
		},
	},
	{
		Id = "Area4",
		Progression = 4,
		CFrame = CFrame.new(-218.41, 0, 0),
		Size = Vector2.new(107.8594, 110.448),
		MaxZombies = 85,
		SpawnInterval = 2,
		GroupSize = NumberRange.new(4, 8),
		GroupRadius = 14,
		MinPlayerDistance = 32,
		ZombieWeights = {
			{ Name = "Walker", Weight = 8 },
			{ Name = "Runner", Weight = 8 },
			{ Name = "Brute", Weight = 7 },
			{ Name = "Spitter", Weight = 6 },
			{ Name = "Charger", Weight = 8 },
			{ Name = "Screamer", Weight = 4 },
			{ Name = "Tank", Weight = 4 },
			{ Name = "Leaper", Weight = 5 },
			{ Name = "Shielder", Weight = 7 },
			{ Name = "Bomber", Weight = 6 },
			{ Name = "Grabber", Weight = 6 },
			{ Name = "Summoner", Weight = 4 },
			{ Name = "Splitter", Weight = 5 },
			{ Name = "Burrower", Weight = 5 },
			{ Name = "Frenzy", Weight = 6 },
			{ Name = "Medic", Weight = 4 },
			{ Name = "Hardened", Weight = 6 },
			{ Name = "Dodger", Weight = 5 },
		},
	},
}

return ZombieAreas
