local CleaningConfig = {
	AutoCompletionThreshold = 0.8,
	BrushRadiusPixels = 72,
	CameraFieldOfView = 70,
	MinimumItemCameraDistance = 3.9,
	ItemCameraDistancePerStud = 0.42,
	ItemVerticalOffset = -0.45,
	ItemTiltDegrees = -8,
	SprayVFXWidthScale = 1,
	SprayEndpointResponsiveness = 24,
	StepTransitionDelay = 0.45,
	FullCompletionDelay = 1,
	DirtDamageSoundName = "Hooked",
	Tools = {
		{
			Id = "Spray",
			DisplayName = "Spray",
			TemplateName = "SprayBottle",
			VFXFolderName = "SprayBottle",
			VFXName = "WaterEffect",
			VFXStartPartName = "EffectStart",
			LoopSoundName = "SprayLoop",
			RadiusPixels = 72,
			StrengthPerSecond = 4,
			VFXWidthScale = 1,
		},
		{
			Id = "SprayPaint",
			DisplayName = "Spray Paint",
			TemplateName = "SprayPaint",
			VFXFolderName = "SprayPaint",
			VFXName = "Paint",
			VFXStartPartName = "EffectStart",
			LoopSoundName = "SprayPaintLoop",
			RadiusPixels = 72,
			StrengthPerSecond = 4,
			VFXWidthScale = 1,
		},
	},
	Steps = {
		{
			Id = "Spray",
			Type = "Dirt",
			DisplayName = "Spraying",
			ToolId = "Spray",
			CompletionSoundName = "Reward1",
		},
		{
			Id = "SprayPaint",
			Type = "Paint",
			DisplayName = "Restoring Paint",
			ToolId = "SprayPaint",
			TargetHP = 2,
			DirtColor = Color3.fromRGB(105, 72, 43),
			DirtAmountMinimum = 0.4,
			DirtAmountMaximum = 0.8,
			CompletionSoundName = "Reward1",
		},
	},
	FullCompletion = {
		SoundNames = { "Reward5", "Confetti" },
		ParticleToolTemplateName = "SprayBottle",
		ParticlePartName = "EffectStart",
		ParticleCount = 40,
	},
}

return CleaningConfig
