export type ItemInfo = {
	Id: number,
	Name: string,
	AssetName: string,
	Rarity: string,
	RestorationSteps: { string },
	ChanceWeight: number,
	Price: number,
	GuestPay: number,
	MoveSpeed: number,
	CarryOffset: CFrame?,
	DirtHP: number,
}

local ItemsInfo: { ItemInfo } = {
	{
		Id = 1,
		Name = "Wrench",
		AssetName = "Wrench",
		Rarity = "Common",
		RestorationSteps = { "Spray" },
		ChanceWeight = 34,
		Price = 25,
		GuestPay = 2,
		MoveSpeed = 8,
		DirtHP = 1,
	},
	{
		Id = 2,
		Name = "Knife",
		AssetName = "Knife",
		Rarity = "Uncommon",
		RestorationSteps = { "Spray" },
		ChanceWeight = 18,
		Price = 60,
		GuestPay = 6,
		MoveSpeed = 8,
		DirtHP = 1.5,
	},
	{
		Id = 3,
		Name = "Hammer",
		AssetName = "Hammer",
		Rarity = "Rare",
		RestorationSteps = { "Spray", "SprayPaint" },
		ChanceWeight = 9,
		Price = 130,
		GuestPay = 15,
		MoveSpeed = 8,
		DirtHP = 2,
	},
	{
		Id = 4,
		Name = "Cleaver",
		AssetName = "Cleaver",
		Rarity = "Epic",
		RestorationSteps = { "SprayPaint", "Sponge" },
		ChanceWeight = 4.5,
		Price = 240,
		GuestPay = 32,
		MoveSpeed = 8,
		DirtHP = 2.5,
	},
	{
		Id = 5,
		Name = "Basketball",
		AssetName = "Basketball",
		Rarity = "Common",
		RestorationSteps = { "Spray" },
		ChanceWeight = 30,
		Price = 35,
		GuestPay = 3,
		MoveSpeed = 8,
		DirtHP = 1,
	},
	{
		Id = 6,
		Name = "Toaster",
		AssetName = "Toaster",
		Rarity = "Common",
		RestorationSteps = { "Spray" },
		ChanceWeight = 26,
		Price = 45,
		GuestPay = 4,
		MoveSpeed = 8,
		DirtHP = 1,
	},
	{
		Id = 7,
		Name = "Shovel",
		AssetName = "Shovel",
		Rarity = "Uncommon",
		RestorationSteps = { "Spray" },
		ChanceWeight = 16,
		Price = 75,
		GuestPay = 8,
		MoveSpeed = 8,
		DirtHP = 1.5,
	},
	{
		Id = 8,
		Name = "Toy Car",
		AssetName = "Toy Car",
		Rarity = "Uncommon",
		RestorationSteps = { "Spray" },
		ChanceWeight = 14,
		Price = 90,
		GuestPay = 10,
		MoveSpeed = 8,
		DirtHP = 1.5,
	},
	{
		Id = 9,
		Name = "Radio",
		AssetName = "Radio",
		Rarity = "Rare",
		RestorationSteps = { "Spray", "Sponge" },
		ChanceWeight = 8,
		Price = 160,
		GuestPay = 20,
		MoveSpeed = 8,
		DirtHP = 2,
	},
	{
		Id = 10,
		Name = "Watch",
		AssetName = "Watch",
		Rarity = "Epic",
		RestorationSteps = { "Spray", "SprayPaint" },
		ChanceWeight = 4,
		Price = 300,
		GuestPay = 42,
		MoveSpeed = 8,
		DirtHP = 2.5,
	},
	{
		Id = 11,
		Name = "Sword",
		AssetName = "Sword",
		Rarity = "Legendary",
		RestorationSteps = { "Spray", "SprayPaint" },
		ChanceWeight = 2.2,
		Price = 500,
		GuestPay = 80,
		MoveSpeed = 8,
		DirtHP = 3,
	},
	{
		Id = 12,
		Name = "Gun",
		AssetName = "Gun",
		Rarity = "Mythic",
		RestorationSteps = { "SprayPaint", "Sponge" },
		ChanceWeight = 0.9,
		Price = 900,
		GuestPay = 160,
		MoveSpeed = 8,
		DirtHP = 3.5,
	},
	{
		Id = 13,
		Name = "Anchor",
		AssetName = "Anchor",
		Rarity = "Secret",
		RestorationSteps = { "Spray", "SprayPaint" },
		ChanceWeight = 0.2,
		Price = 1800,
		GuestPay = 400,
		MoveSpeed = 8,
		DirtHP = 4,
	},
	{
		Id = 14,
		Name = "Alarm Clock",
		AssetName = "Alarm Clock",
		Rarity = "Common",
		RestorationSteps = { "Spray" },
		ChanceWeight = 30,
		Price = 30,
		GuestPay = 3,
		MoveSpeed = 8,
		DirtHP = 1,
	},
	{
		Id = 15,
		Name = "Binoculars",
		AssetName = "Binoculars",
		Rarity = "Uncommon",
		RestorationSteps = { "Spray" },
		ChanceWeight = 15,
		Price = 85,
		GuestPay = 9,
		MoveSpeed = 8,
		DirtHP = 1.5,
	},
	{
		Id = 16,
		Name = "Bottle",
		AssetName = "Bottle",
		Rarity = "Common",
		RestorationSteps = { "Spray" },
		ChanceWeight = 32,
		Price = 28,
		GuestPay = 3,
		MoveSpeed = 8,
		DirtHP = 1,
	},
	{
		Id = 17,
		Name = "Camera",
		AssetName = "Camera",
		Rarity = "Rare",
		RestorationSteps = { "Spray", "SprayPaint" },
		ChanceWeight = 8,
		Price = 175,
		GuestPay = 22,
		MoveSpeed = 8,
		DirtHP = 2,
	},
	{
		Id = 18,
		Name = "Desk Fan",
		AssetName = "Desk Fan",
		Rarity = "Common",
		RestorationSteps = { "Spray" },
		ChanceWeight = 25,
		Price = 48,
		GuestPay = 5,
		MoveSpeed = 8,
		DirtHP = 1,
	},
	{
		Id = 19,
		Name = "Drone",
		AssetName = "Drone",
		Rarity = "Epic",
		RestorationSteps = { "Spray", "SprayPaint", "Sponge" },
		ChanceWeight = 3.8,
		Price = 325,
		GuestPay = 48,
		MoveSpeed = 8,
		DirtHP = 2.5,
	},
	{
		Id = 20,
		Name = "Flashlight",
		AssetName = "Flashlight",
		Rarity = "Common",
		RestorationSteps = { "Spray" },
		ChanceWeight = 28,
		Price = 40,
		GuestPay = 4,
		MoveSpeed = 8,
		DirtHP = 1,
	},
	{
		Id = 21,
		Name = "Gold Bar",
		AssetName = "Gold Bar",
		Rarity = "Legendary",
		RestorationSteps = { "SprayPaint", "Sponge" },
		ChanceWeight = 1.8,
		Price = 650,
		GuestPay = 105,
		MoveSpeed = 8,
		DirtHP = 3,
	},
	{
		Id = 22,
		Name = "Iron Bar",
		AssetName = "Iron Bar",
		Rarity = "Rare",
		RestorationSteps = { "Spray", "Sponge" },
		ChanceWeight = 7.5,
		Price = 190,
		GuestPay = 25,
		MoveSpeed = 8,
		DirtHP = 2,
	},
	{
		Id = 23,
		Name = "Magnifying Glass",
		AssetName = "MagnifyingGlass",
		Rarity = "Uncommon",
		RestorationSteps = { "Spray" },
		ChanceWeight = 17,
		Price = 70,
		GuestPay = 7,
		MoveSpeed = 8,
		DirtHP = 1.5,
	},
	{
		Id = 24,
		Name = "Mango",
		AssetName = "Mango",
		Rarity = "Common",
		RestorationSteps = { "Spray" },
		ChanceWeight = 31,
		Price = 32,
		GuestPay = 3,
		MoveSpeed = 8,
		DirtHP = 1,
	},
	{
		Id = 25,
		Name = "Medal",
		AssetName = "Medal",
		Rarity = "Rare",
		RestorationSteps = { "SprayPaint", "Sponge" },
		ChanceWeight = 8.5,
		Price = 150,
		GuestPay = 18,
		MoveSpeed = 8,
		DirtHP = 2,
	},
	{
		Id = 26,
		Name = "Microphone",
		AssetName = "Microphone",
		Rarity = "Uncommon",
		RestorationSteps = { "Spray" },
		ChanceWeight = 13,
		Price = 100,
		GuestPay = 12,
		MoveSpeed = 8,
		DirtHP = 1.5,
	},
	{
		Id = 27,
		Name = "Old Keyboard",
		AssetName = "Old Keyboard",
		Rarity = "Uncommon",
		RestorationSteps = { "Spray" },
		ChanceWeight = 14,
		Price = 95,
		GuestPay = 11,
		MoveSpeed = 8,
		DirtHP = 1.5,
	},
	{
		Id = 28,
		Name = "Phone",
		AssetName = "Phone",
		Rarity = "Epic",
		RestorationSteps = { "Spray", "SprayPaint" },
		ChanceWeight = 4.2,
		Price = 275,
		GuestPay = 38,
		MoveSpeed = 8,
		DirtHP = 2.5,
	},
	{
		Id = 29,
		Name = "TV",
		AssetName = "TV",
		Rarity = "Rare",
		RestorationSteps = { "Spray", "SprayPaint", "Sponge" },
		ChanceWeight = 6.5,
		Price = 220,
		GuestPay = 30,
		MoveSpeed = 8,
		DirtHP = 2,
	},
	{
		Id = 30,
		Name = "Toy Plane",
		AssetName = "Toy Plane",
		Rarity = "Uncommon",
		RestorationSteps = { "Spray" },
		ChanceWeight = 16,
		Price = 80,
		GuestPay = 8,
		MoveSpeed = 8,
		DirtHP = 1.5,
	},
	{
		Id = 31,
		Name = "Toy Train",
		AssetName = "Toy Train",
		Rarity = "Uncommon",
		RestorationSteps = { "Spray" },
		ChanceWeight = 15,
		Price = 88,
		GuestPay = 10,
		MoveSpeed = 8,
		DirtHP = 1.5,
	},
	{
		Id = 32,
		Name = "Trophy",
		AssetName = "Trophy",
		Rarity = "Epic",
		RestorationSteps = { "SprayPaint", "Sponge" },
		ChanceWeight = 4,
		Price = 290,
		GuestPay = 40,
		MoveSpeed = 8,
		DirtHP = 2.5,
	},
	{
		Id = 33,
		Name = "Vase",
		AssetName = "Vase",
		Rarity = "Rare",
		RestorationSteps = { "Spray", "SprayPaint" },
		ChanceWeight = 7,
		Price = 205,
		GuestPay = 27,
		MoveSpeed = 8,
		DirtHP = 2,
	},
	{
		Id = 34,
		Name = "Dinosaur Egg",
		AssetName = "Dinosaur Egg",
		Rarity = "Secret",
		RestorationSteps = { "Spray", "SprayPaint", "Sponge" },
		ChanceWeight = 0.15,
		Price = 2_000,
		GuestPay = 450,
		MoveSpeed = 8,
		DirtHP = 4,
	},
	{
		Id = 35,
		Name = "Electric Guitar",
		AssetName = "Electric Guitar",
		Rarity = "Epic",
		RestorationSteps = { "Spray", "SprayPaint" },
		ChanceWeight = 3.5,
		Price = 340,
		GuestPay = 50,
		MoveSpeed = 8,
		DirtHP = 2.5,
	},
	{
		Id = 36,
		Name = "Fire Hydrant",
		AssetName = "Fire Hydrant",
		Rarity = "Rare",
		RestorationSteps = { "Spray", "Sponge" },
		ChanceWeight = 7,
		Price = 210,
		GuestPay = 28,
		MoveSpeed = 8,
		DirtHP = 2,
	},
	{
		Id = 37,
		Name = "Gramophone",
		AssetName = "Gramophone",
		Rarity = "Legendary",
		RestorationSteps = { "Spray", "SprayPaint", "Sponge" },
		ChanceWeight = 1.7,
		Price = 700,
		GuestPay = 115,
		MoveSpeed = 8,
		DirtHP = 3,
	},
	{
		Id = 38,
		Name = "Grandfather Clock",
		AssetName = "Grandfather Clock",
		Rarity = "Mythic",
		RestorationSteps = { "Spray", "SprayPaint", "Sponge" },
		ChanceWeight = 0.7,
		Price = 1_100,
		GuestPay = 190,
		MoveSpeed = 8,
		DirtHP = 3.5,
	},
	{
		Id = 39,
		Name = "Record Player",
		AssetName = "Record Player",
		Rarity = "Rare",
		RestorationSteps = { "Spray", "SprayPaint", "Sponge" },
		ChanceWeight = 6.8,
		Price = 225,
		GuestPay = 31,
		MoveSpeed = 8,
		DirtHP = 2,
	},
	{
		Id = 40,
		Name = "Rotary Telephone",
		AssetName = "Rotary Telephone",
		Rarity = "Rare",
		RestorationSteps = { "Spray", "Sponge" },
		ChanceWeight = 8,
		Price = 180,
		GuestPay = 23,
		MoveSpeed = 8,
		DirtHP = 2,
	},
	{
		Id = 41,
		Name = "Statue",
		AssetName = "Statue",
		Rarity = "Legendary",
		RestorationSteps = { "Spray", "SprayPaint" },
		ChanceWeight = 1.5,
		Price = 750,
		GuestPay = 125,
		MoveSpeed = 8,
		DirtHP = 3,
	},
	{
		Id = 42,
		Name = "Telescope",
		AssetName = "Telescope",
		Rarity = "Epic",
		RestorationSteps = { "Spray", "Sponge" },
		ChanceWeight = 3.6,
		Price = 360,
		GuestPay = 52,
		MoveSpeed = 8,
		DirtHP = 2.5,
	},
	{
		Id = 43,
		Name = "Typewriter",
		AssetName = "Typewriter",
		Rarity = "Epic",
		RestorationSteps = { "SprayPaint", "Sponge" },
		ChanceWeight = 4.1,
		Price = 310,
		GuestPay = 44,
		MoveSpeed = 8,
		DirtHP = 2.5,
	},
	{
		Id = 44,
		Name = "Washing Machine",
		AssetName = "Washing Machine",
		Rarity = "Uncommon",
		RestorationSteps = { "Spray" },
		ChanceWeight = 12,
		Price = 115,
		GuestPay = 14,
		MoveSpeed = 8,
		DirtHP = 1.5,
	},
	{
		Id = 45,
		Name = "Moon Rock",
		AssetName = "Moon Rock",
		Rarity = "Legendary",
		RestorationSteps = { "Spray", "Sponge" },
		ChanceWeight = 1.4,
		Price = 780,
		GuestPay = 130,
		MoveSpeed = 8,
		DirtHP = 3,
	},
	{
		Id = 46,
		Name = "UFO",
		AssetName = "UFO",
		Rarity = "Secret",
		RestorationSteps = { "Spray", "SprayPaint", "Sponge" },
		ChanceWeight = 0.1,
		Price = 2_400,
		GuestPay = 520,
		MoveSpeed = 8,
		DirtHP = 4,
	},
	{
		Id = 47,
		Name = "TV Remote",
		AssetName = "Tv remote",
		Rarity = "Common",
		RestorationSteps = { "Spray" },
		ChanceWeight = 28,
		Price = 38,
		GuestPay = 4,
		MoveSpeed = 8,
		DirtHP = 1,
	},
	{
		Id = 48,
		Name = "Chainsaw",
		AssetName = "Chainsaw",
		Rarity = "Rare",
		RestorationSteps = { "Spray", "SprayPaint", "Sponge" },
		ChanceWeight = 7,
		Price = 235,
		GuestPay = 32,
		MoveSpeed = 8,
		DirtHP = 2,
	},
	{
		Id = 49,
		Name = "Rocket",
		AssetName = "Rocket",
		Rarity = "Mythic",
		RestorationSteps = { "Spray", "SprayPaint", "Sponge" },
		ChanceWeight = 0.6,
		Price = 1_250,
		GuestPay = 220,
		MoveSpeed = 8,
		DirtHP = 3.5,
	},
	{
		Id = 50,
		Name = "Satellite",
		AssetName = "Satellite",
		Rarity = "Legendary",
		RestorationSteps = { "Spray", "SprayPaint", "Sponge" },
		ChanceWeight = 1.3,
		Price = 850,
		GuestPay = 145,
		MoveSpeed = 8,
		DirtHP = 3,
	},
	{
		Id = 51,
		Name = "Speaker",
		AssetName = "Speaker",
		Rarity = "Uncommon",
		RestorationSteps = { "Spray" },
		ChanceWeight = 13,
		Price = 110,
		GuestPay = 13,
		MoveSpeed = 8,
		DirtHP = 1.5,
	},
	{
		Id = 52,
		Name = "Mammoth Tusk",
		AssetName = "Mammoth Tusk",
		Rarity = "Legendary",
		RestorationSteps = { "Spray", "Sponge" },
		ChanceWeight = 1.2,
		Price = 720,
		GuestPay = 120,
		MoveSpeed = 8,
		DirtHP = 3,
	},
	{
		Id = 53,
		Name = "Pirate Chest",
		AssetName = "Pirate Chest",
		Rarity = "Epic",
		RestorationSteps = { "Spray", "SprayPaint", "Sponge" },
		ChanceWeight = 3.2,
		Price = 410,
		GuestPay = 60,
		MoveSpeed = 8,
		DirtHP = 2.5,
	},
	{
		Id = 54,
		Name = "Fossil",
		AssetName = "Fossil",
		Rarity = "Epic",
		RestorationSteps = { "Spray", "Sponge" },
		ChanceWeight = 3.4,
		Price = 385,
		GuestPay = 56,
		MoveSpeed = 8,
		DirtHP = 2.5,
	},
	{
		Id = 55,
		Name = "Meteorite",
		AssetName = "Meteorite",
		Rarity = "Mythic",
		RestorationSteps = { "Spray", "SprayPaint", "Sponge" },
		ChanceWeight = 0.55,
		Price = 1_350,
		GuestPay = 240,
		MoveSpeed = 8,
		DirtHP = 3.5,
	},
	{
		Id = 56,
		Name = "Motorcycle",
		AssetName = "Motorcycle",
		Rarity = "Epic",
		RestorationSteps = { "Spray", "SprayPaint", "Sponge" },
		ChanceWeight = 3.3,
		Price = 430,
		GuestPay = 64,
		MoveSpeed = 8,
		DirtHP = 2.5,
	},
	{
		Id = 57,
		Name = "Safe",
		AssetName = "Safe",
		Rarity = "Epic",
		RestorationSteps = { "Spray", "SprayPaint", "Sponge" },
		ChanceWeight = 3.1,
		Price = 450,
		GuestPay = 68,
		MoveSpeed = 8,
		DirtHP = 2.5,
	},
	{
		Id = 58,
		Name = "Air Compressor",
		AssetName = "Air Compressor",
		Rarity = "Rare",
		RestorationSteps = { "Spray", "Sponge" },
		ChanceWeight = 7.5,
		Price = 195,
		GuestPay = 26,
		MoveSpeed = 8,
		DirtHP = 2,
	},
	{
		Id = 59,
		Name = "Ancient Coin",
		AssetName = "Ancient Coin",
		Rarity = "Legendary",
		RestorationSteps = { "Spray", "SprayPaint", "Sponge" },
		ChanceWeight = 1.6,
		Price = 740,
		GuestPay = 122,
		MoveSpeed = 8,
		DirtHP = 3,
	},
	{
		Id = 60,
		Name = "Ancient Idol",
		AssetName = "Ancient Idol",
		Rarity = "Mythic",
		RestorationSteps = { "Spray", "SprayPaint", "Sponge" },
		ChanceWeight = 0.65,
		Price = 1_180,
		GuestPay = 205,
		MoveSpeed = 8,
		DirtHP = 3.5,
	},
	{
		Id = 61,
		Name = "Antique Wardrobe",
		AssetName = "Antique Wardrobe",
		Rarity = "Epic",
		RestorationSteps = { "Spray", "SprayPaint", "Sponge" },
		ChanceWeight = 3.4,
		Price = 390,
		GuestPay = 57,
		MoveSpeed = 8,
		DirtHP = 2.5,
	},
	{
		Id = 62,
		Name = "Arcade Machine",
		AssetName = "Arcade Machine",
		Rarity = "Epic",
		RestorationSteps = { "Spray", "SprayPaint", "Sponge" },
		ChanceWeight = 3.2,
		Price = 420,
		GuestPay = 62,
		MoveSpeed = 8,
		DirtHP = 2.5,
	},
	{
		Id = 63,
		Name = "Astrolabe",
		AssetName = "Astrolabe",
		Rarity = "Legendary",
		RestorationSteps = { "Spray", "SprayPaint", "Sponge" },
		ChanceWeight = 1.5,
		Price = 770,
		GuestPay = 128,
		MoveSpeed = 8,
		DirtHP = 3,
	},
	{
		Id = 64,
		Name = "Baseball Bat",
		AssetName = "Baseball Bat",
		Rarity = "Common",
		RestorationSteps = { "Spray" },
		ChanceWeight = 29,
		Price = 36,
		GuestPay = 4,
		MoveSpeed = 8,
		DirtHP = 1,
	},
	{
		Id = 65,
		Name = "Bench Vise",
		AssetName = "Bench Vise",
		Rarity = "Uncommon",
		RestorationSteps = { "Spray" },
		ChanceWeight = 14,
		Price = 92,
		GuestPay = 10,
		MoveSpeed = 8,
		DirtHP = 1.5,
	},
	{
		Id = 66,
		Name = "Bicycle",
		AssetName = "Bicycle",
		Rarity = "Rare",
		RestorationSteps = { "Spray", "SprayPaint", "Sponge" },
		ChanceWeight = 7.2,
		Price = 215,
		GuestPay = 29,
		MoveSpeed = 8,
		DirtHP = 2,
	},
	{
		Id = 67,
		Name = "Boxing Gloves",
		AssetName = "Boxing Gloves",
		Rarity = "Uncommon",
		RestorationSteps = { "Spray" },
		ChanceWeight = 15,
		Price = 82,
		GuestPay = 9,
		MoveSpeed = 8,
		DirtHP = 1.5,
	},
	{
		Id = 68,
		Name = "Bulldozer",
		AssetName = "Bulldozer",
		Rarity = "Legendary",
		RestorationSteps = { "Spray", "SprayPaint", "Sponge" },
		ChanceWeight = 1.3,
		Price = 830,
		GuestPay = 140,
		MoveSpeed = 8,
		DirtHP = 3,
	},
	{
		Id = 69,
		Name = "Ceiling Fan",
		AssetName = "Ceiling Fan",
		Rarity = "Uncommon",
		RestorationSteps = { "Spray" },
		ChanceWeight = 13,
		Price = 105,
		GuestPay = 12,
		MoveSpeed = 8,
		DirtHP = 1.5,
	},
	{
		Id = 70,
		Name = "Desk",
		AssetName = "Desk",
		Rarity = "Uncommon",
		RestorationSteps = { "Spray" },
		ChanceWeight = 12,
		Price = 112,
		GuestPay = 14,
		MoveSpeed = 8,
		DirtHP = 1.5,
	},
	{
		Id = 71,
		Name = "Diving Helmet",
		AssetName = "Diving Helmet",
		Rarity = "Epic",
		RestorationSteps = { "Spray", "SprayPaint", "Sponge" },
		ChanceWeight = 3.6,
		Price = 365,
		GuestPay = 53,
		MoveSpeed = 8,
		DirtHP = 2.5,
	},
	{
		Id = 72,
		Name = "Drill Press",
		AssetName = "Drill Press",
		Rarity = "Rare",
		RestorationSteps = { "Spray", "Sponge" },
		ChanceWeight = 6.8,
		Price = 230,
		GuestPay = 31,
		MoveSpeed = 8,
		DirtHP = 2,
	},
	{
		Id = 73,
		Name = "Factory Machine",
		AssetName = "Factory Machine",
		Rarity = "Mythic",
		RestorationSteps = { "Spray", "SprayPaint", "Sponge" },
		ChanceWeight = 0.6,
		Price = 1_300,
		GuestPay = 230,
		MoveSpeed = 8,
		DirtHP = 3.5,
	},
	{
		Id = 74,
		Name = "Forklift",
		AssetName = "Forklift",
		Rarity = "Epic",
		RestorationSteps = { "Spray", "SprayPaint", "Sponge" },
		ChanceWeight = 3.1,
		Price = 445,
		GuestPay = 67,
		MoveSpeed = 8,
		DirtHP = 2.5,
	},
	{
		Id = 75,
		Name = "Game Console",
		AssetName = "Game Console",
		Rarity = "Rare",
		RestorationSteps = { "Spray", "SprayPaint" },
		ChanceWeight = 8,
		Price = 180,
		GuestPay = 23,
		MoveSpeed = 8,
		DirtHP = 2,
	},
	{
		Id = 76,
		Name = "Garden Fountain",
		AssetName = "Garden Fountain",
		Rarity = "Epic",
		RestorationSteps = { "Spray", "Sponge" },
		ChanceWeight = 3.5,
		Price = 375,
		GuestPay = 55,
		MoveSpeed = 8,
		DirtHP = 2.5,
	},
	{
		Id = 77,
		Name = "Giant Skull",
		AssetName = "Giant Skull",
		Rarity = "Secret",
		RestorationSteps = { "Spray", "SprayPaint", "Sponge" },
		ChanceWeight = 0.14,
		Price = 2_150,
		GuestPay = 475,
		MoveSpeed = 8,
		DirtHP = 4,
	},
	{
		Id = 78,
		Name = "Go-Kart",
		AssetName = "Go-Kart",
		Rarity = "Rare",
		RestorationSteps = { "Spray", "SprayPaint", "Sponge" },
		ChanceWeight = 6.7,
		Price = 228,
		GuestPay = 31,
		MoveSpeed = 8,
		DirtHP = 2,
	},
	{
		Id = 79,
		Name = "Grand Piano",
		AssetName = "Grand Piano",
		Rarity = "Mythic",
		RestorationSteps = { "Spray", "SprayPaint", "Sponge" },
		ChanceWeight = 0.58,
		Price = 1_320,
		GuestPay = 235,
		MoveSpeed = 8,
		DirtHP = 3.5,
	},
	{
		Id = 80,
		Name = "Harmonica",
		AssetName = "Harmonica",
		Rarity = "Common",
		RestorationSteps = { "Spray" },
		ChanceWeight = 30,
		Price = 34,
		GuestPay = 3,
		MoveSpeed = 8,
		DirtHP = 1,
	},
	{
		Id = 81,
		Name = "Helicopter",
		AssetName = "Helicopter",
		Rarity = "Mythic",
		RestorationSteps = { "Spray", "SprayPaint", "Sponge" },
		ChanceWeight = 0.55,
		Price = 1_400,
		GuestPay = 250,
		MoveSpeed = 8,
		DirtHP = 3.5,
	},
	{
		Id = 82,
		Name = "Lawn Mower",
		AssetName = "Lawn Mower",
		Rarity = "Uncommon",
		RestorationSteps = { "Spray" },
		ChanceWeight = 12,
		Price = 118,
		GuestPay = 14,
		MoveSpeed = 8,
		DirtHP = 1.5,
	},
	{
		Id = 83,
		Name = "Microscope",
		AssetName = "Microscope",
		Rarity = "Rare",
		RestorationSteps = { "Spray", "SprayPaint" },
		ChanceWeight = 7.8,
		Price = 185,
		GuestPay = 24,
		MoveSpeed = 8,
		DirtHP = 2,
	},
	{
		Id = 84,
		Name = "Military Tank",
		AssetName = "Military Tank",
		Rarity = "Secret",
		RestorationSteps = { "Spray", "SprayPaint", "Sponge" },
		ChanceWeight = 0.1,
		Price = 2_500,
		GuestPay = 550,
		MoveSpeed = 8,
		DirtHP = 4,
	},
	{
		Id = 85,
		Name = "Oil Barrel",
		AssetName = "Oil Barrel",
		Rarity = "Uncommon",
		RestorationSteps = { "Spray" },
		ChanceWeight = 13,
		Price = 108,
		GuestPay = 13,
		MoveSpeed = 8,
		DirtHP = 1.5,
	},
	{
		Id = 86,
		Name = "Pinball Machine",
		AssetName = "Pinball Machine",
		Rarity = "Epic",
		RestorationSteps = { "Spray", "SprayPaint", "Sponge" },
		ChanceWeight = 3.3,
		Price = 405,
		GuestPay = 60,
		MoveSpeed = 8,
		DirtHP = 2.5,
	},
	{
		Id = 87,
		Name = "RC Car",
		AssetName = "RC Car",
		Rarity = "Uncommon",
		RestorationSteps = { "Spray" },
		ChanceWeight = 16,
		Price = 78,
		GuestPay = 8,
		MoveSpeed = 8,
		DirtHP = 1.5,
	},
	{
		Id = 88,
		Name = "Rocking Chair",
		AssetName = "Rocking Chair",
		Rarity = "Rare",
		RestorationSteps = { "Spray", "Sponge" },
		ChanceWeight = 7,
		Price = 218,
		GuestPay = 29,
		MoveSpeed = 8,
		DirtHP = 2,
	},
	{
		Id = 89,
		Name = "Royal Crown",
		AssetName = "Royal Crown",
		Rarity = "Secret",
		RestorationSteps = { "Spray", "SprayPaint", "Sponge" },
		ChanceWeight = 0.12,
		Price = 2_300,
		GuestPay = 510,
		MoveSpeed = 8,
		DirtHP = 4,
	},
	{
		Id = 90,
		Name = "Satellite Dish",
		AssetName = "Satellite Dish",
		Rarity = "Epic",
		RestorationSteps = { "Spray", "SprayPaint", "Sponge" },
		ChanceWeight = 3.4,
		Price = 395,
		GuestPay = 58,
		MoveSpeed = 8,
		DirtHP = 2.5,
	},
	{
		Id = 91,
		Name = "Shopping Cart",
		AssetName = "Shopping Cart",
		Rarity = "Common",
		RestorationSteps = { "Spray" },
		ChanceWeight = 25,
		Price = 50,
		GuestPay = 5,
		MoveSpeed = 8,
		DirtHP = 1,
	},
	{
		Id = 92,
		Name = "Steam Engine",
		AssetName = "Steam Engine",
		Rarity = "Legendary",
		RestorationSteps = { "Spray", "SprayPaint", "Sponge" },
		ChanceWeight = 1.2,
		Price = 880,
		GuestPay = 150,
		MoveSpeed = 8,
		DirtHP = 3,
	},
	{
		Id = 93,
		Name = "Surfboard",
		AssetName = "Surfboard",
		Rarity = "Uncommon",
		RestorationSteps = { "Spray" },
		ChanceWeight = 15,
		Price = 86,
		GuestPay = 9,
		MoveSpeed = 8,
		DirtHP = 1.5,
	},
	{
		Id = 94,
		Name = "Teddy Bear",
		AssetName = "Teddy Bear",
		Rarity = "Common",
		RestorationSteps = { "Spray" },
		ChanceWeight = 27,
		Price = 42,
		GuestPay = 4,
		MoveSpeed = 8,
		DirtHP = 1,
	},
	{
		Id = 95,
		Name = "Toolbox",
		AssetName = "Toolbox",
		Rarity = "Common",
		RestorationSteps = { "Spray" },
		ChanceWeight = 26,
		Price = 46,
		GuestPay = 5,
		MoveSpeed = 8,
		DirtHP = 1,
	},
	{
		Id = 96,
		Name = "Tractor",
		AssetName = "Tractor",
		Rarity = "Epic",
		RestorationSteps = { "Spray", "SprayPaint", "Sponge" },
		ChanceWeight = 3,
		Price = 460,
		GuestPay = 70,
		MoveSpeed = 8,
		DirtHP = 2.5,
	},
	{
		Id = 97,
		Name = "Trumpet",
		AssetName = "Trumpet",
		Rarity = "Rare",
		RestorationSteps = { "Spray", "SprayPaint" },
		ChanceWeight = 8.2,
		Price = 170,
		GuestPay = 21,
		MoveSpeed = 8,
		DirtHP = 2,
	},
	{
		Id = 98,
		Name = "VHS Player",
		AssetName = "VHS Player",
		Rarity = "Uncommon",
		RestorationSteps = { "Spray" },
		ChanceWeight = 14,
		Price = 96,
		GuestPay = 11,
		MoveSpeed = 8,
		DirtHP = 1.5,
	},
	{
		Id = 99,
		Name = "Welding Mask",
		AssetName = "Welding Mask",
		Rarity = "Uncommon",
		RestorationSteps = { "Spray" },
		ChanceWeight = 13,
		Price = 102,
		GuestPay = 12,
		MoveSpeed = 8,
		DirtHP = 1.5,
	},
	{
		Id = 100,
		Name = "Wheelbarrow",
		AssetName = "Wheelbarrow",
		Rarity = "Common",
		RestorationSteps = { "Spray" },
		ChanceWeight = 25,
		Price = 52,
		GuestPay = 5,
		MoveSpeed = 8,
		DirtHP = 1,
	},
}

return ItemsInfo
