export type ItemInfo = {
	Id: number,
	Name: string,
	AssetName: string,
	Rarity: string,
	RestorationSteps: { string },
	ChanceWeight: number,
	Price: number,
	GuestPay: number,
	MoveSpeed: number,
	CarryOffset: CFrame?,
	DirtHP: number,
}

local ItemsInfo: { ItemInfo } = {
	{
		Id = 1,
		Name = "Wrench",
		AssetName = "Wrench",
		Rarity = "Common",
		RestorationSteps = { "Spray" },
		ChanceWeight = 34,
		Price = 25,
		GuestPay = 2,
		MoveSpeed = 8,
		DirtHP = 1,
	},
	{
		Id = 2,
		Name = "Knife",
		AssetName = "Knife",
		Rarity = "Uncommon",
		RestorationSteps = { "SprayPaint", "Sponge" },
		ChanceWeight = 18,
		Price = 60,
		GuestPay = 6,
		MoveSpeed = 8,
		DirtHP = 1.5,
	},
	{
		Id = 3,
		Name = "Hammer",
		AssetName = "Hammer",
		Rarity = "Rare",
		RestorationSteps = { "Spray", "SprayPaint" },
		ChanceWeight = 9,
		Price = 130,
		GuestPay = 15,
		MoveSpeed = 8,
		DirtHP = 2,
	},
	{
		Id = 4,
		Name = "Cleaver",
		AssetName = "Cleaver",
		Rarity = "Epic",
		RestorationSteps = { "SprayPaint", "Sponge" },
		ChanceWeight = 4.5,
		Price = 240,
		GuestPay = 32,
		MoveSpeed = 8,
		DirtHP = 2.5,
	},
	{
		Id = 5,
		Name = "Basketball",
		AssetName = "Basketball",
		Rarity = "Common",
		RestorationSteps = { "Spray" },
		ChanceWeight = 30,
		Price = 35,
		GuestPay = 3,
		MoveSpeed = 8,
		DirtHP = 1,
	},
	{
		Id = 6,
		Name = "Toaster",
		AssetName = "Toaster",
		Rarity = "Common",
		RestorationSteps = { "Sponge" },
		ChanceWeight = 26,
		Price = 45,
		GuestPay = 4,
		MoveSpeed = 8,
		DirtHP = 1,
	},
	{
		Id = 7,
		Name = "Shovel",
		AssetName = "Shovel",
		Rarity = "Uncommon",
		RestorationSteps = { "Spray" },
		ChanceWeight = 16,
		Price = 75,
		GuestPay = 8,
		MoveSpeed = 8,
		DirtHP = 1.5,
	},
	{
		Id = 8,
		Name = "Toy Car",
		AssetName = "Toy Car",
		Rarity = "Uncommon",
		RestorationSteps = { "Spray", "SprayPaint", "Sponge" },
		ChanceWeight = 14,
		Price = 90,
		GuestPay = 10,
		MoveSpeed = 8,
		DirtHP = 1.5,
	},
	{
		Id = 9,
		Name = "Radio",
		AssetName = "Radio",
		Rarity = "Rare",
		RestorationSteps = { "Spray", "Sponge" },
		ChanceWeight = 8,
		Price = 160,
		GuestPay = 20,
		MoveSpeed = 8,
		DirtHP = 2,
	},
	{
		Id = 10,
		Name = "Watch",
		AssetName = "Watch",
		Rarity = "Epic",
		RestorationSteps = { "Spray", "SprayPaint" },
		ChanceWeight = 4,
		Price = 300,
		GuestPay = 42,
		MoveSpeed = 8,
		DirtHP = 2.5,
	},
	{
		Id = 11,
		Name = "Sword",
		AssetName = "Sword",
		Rarity = "Legendary",
		RestorationSteps = { "Spray", "SprayPaint" },
		ChanceWeight = 2.2,
		Price = 500,
		GuestPay = 80,
		MoveSpeed = 8,
		DirtHP = 3,
	},
	{
		Id = 12,
		Name = "Gun",
		AssetName = "Gun",
		Rarity = "Mythic",
		RestorationSteps = { "SprayPaint", "Sponge" },
		ChanceWeight = 0.9,
		Price = 900,
		GuestPay = 160,
		MoveSpeed = 8,
		DirtHP = 3.5,
	},
	{
		Id = 13,
		Name = "Anchor",
		AssetName = "Anchor",
		Rarity = "Secret",
		RestorationSteps = { "Spray", "SprayPaint" },
		ChanceWeight = 0.2,
		Price = 1800,
		GuestPay = 400,
		MoveSpeed = 8,
		DirtHP = 4,
	},
	{
		Id = 14,
		Name = "Alarm Clock",
		AssetName = "Alarm Clock",
		Rarity = "Common",
		RestorationSteps = { "Spray" },
		ChanceWeight = 30,
		Price = 30,
		GuestPay = 3,
		MoveSpeed = 8,
		DirtHP = 1,
	},
	{
		Id = 15,
		Name = "Binoculars",
		AssetName = "Binoculars",
		Rarity = "Uncommon",
		RestorationSteps = { "Spray", "Sponge" },
		ChanceWeight = 15,
		Price = 85,
		GuestPay = 9,
		MoveSpeed = 8,
		DirtHP = 1.5,
	},
	{
		Id = 16,
		Name = "Bottle",
		AssetName = "Bottle",
		Rarity = "Common",
		RestorationSteps = { "Spray" },
		ChanceWeight = 32,
		Price = 28,
		GuestPay = 3,
		MoveSpeed = 8,
		DirtHP = 1,
	},
	{
		Id = 17,
		Name = "Camera",
		AssetName = "Camera",
		Rarity = "Rare",
		RestorationSteps = { "Spray", "SprayPaint" },
		ChanceWeight = 8,
		Price = 175,
		GuestPay = 22,
		MoveSpeed = 8,
		DirtHP = 2,
	},
	{
		Id = 18,
		Name = "Desk Fan",
		AssetName = "Desk Fan",
		Rarity = "Common",
		RestorationSteps = { "Spray", "Sponge" },
		ChanceWeight = 25,
		Price = 48,
		GuestPay = 5,
		MoveSpeed = 8,
		DirtHP = 1,
	},
	{
		Id = 19,
		Name = "Drone",
		AssetName = "Drone",
		Rarity = "Epic",
		RestorationSteps = { "Spray", "SprayPaint", "Sponge" },
		ChanceWeight = 3.8,
		Price = 325,
		GuestPay = 48,
		MoveSpeed = 8,
		DirtHP = 2.5,
	},
	{
		Id = 20,
		Name = "Flashlight",
		AssetName = "Flashlight",
		Rarity = "Common",
		RestorationSteps = { "Spray" },
		ChanceWeight = 28,
		Price = 40,
		GuestPay = 4,
		MoveSpeed = 8,
		DirtHP = 1,
	},
	{
		Id = 21,
		Name = "Gold Bar",
		AssetName = "Gold Bar",
		Rarity = "Legendary",
		RestorationSteps = { "SprayPaint", "Sponge" },
		ChanceWeight = 1.8,
		Price = 650,
		GuestPay = 105,
		MoveSpeed = 8,
		DirtHP = 3,
	},
	{
		Id = 22,
		Name = "Iron Bar",
		AssetName = "Iron Bar",
		Rarity = "Rare",
		RestorationSteps = { "Spray", "Sponge" },
		ChanceWeight = 7.5,
		Price = 190,
		GuestPay = 25,
		MoveSpeed = 8,
		DirtHP = 2,
	},
	{
		Id = 23,
		Name = "Magnifying Glass",
		AssetName = "MagnifyingGlass",
		Rarity = "Uncommon",
		RestorationSteps = { "Spray", "Sponge" },
		ChanceWeight = 17,
		Price = 70,
		GuestPay = 7,
		MoveSpeed = 8,
		DirtHP = 1.5,
	},
	{
		Id = 24,
		Name = "Mango",
		AssetName = "Mango",
		Rarity = "Common",
		RestorationSteps = { "Spray" },
		ChanceWeight = 31,
		Price = 32,
		GuestPay = 3,
		MoveSpeed = 8,
		DirtHP = 1,
	},
	{
		Id = 25,
		Name = "Medal",
		AssetName = "Medal",
		Rarity = "Rare",
		RestorationSteps = { "SprayPaint", "Sponge" },
		ChanceWeight = 8.5,
		Price = 150,
		GuestPay = 18,
		MoveSpeed = 8,
		DirtHP = 2,
	},
	{
		Id = 26,
		Name = "Microphone",
		AssetName = "Microphone",
		Rarity = "Uncommon",
		RestorationSteps = { "Spray", "SprayPaint" },
		ChanceWeight = 13,
		Price = 100,
		GuestPay = 12,
		MoveSpeed = 8,
		DirtHP = 1.5,
	},
	{
		Id = 27,
		Name = "Old Keyboard",
		AssetName = "Old Keyboard",
		Rarity = "Uncommon",
		RestorationSteps = { "Spray", "Sponge" },
		ChanceWeight = 14,
		Price = 95,
		GuestPay = 11,
		MoveSpeed = 8,
		DirtHP = 1.5,
	},
	{
		Id = 28,
		Name = "Phone",
		AssetName = "Phone",
		Rarity = "Epic",
		RestorationSteps = { "Spray", "SprayPaint" },
		ChanceWeight = 4.2,
		Price = 275,
		GuestPay = 38,
		MoveSpeed = 8,
		DirtHP = 2.5,
	},
	{
		Id = 29,
		Name = "TV",
		AssetName = "TV",
		Rarity = "Rare",
		RestorationSteps = { "Spray", "SprayPaint", "Sponge" },
		ChanceWeight = 6.5,
		Price = 220,
		GuestPay = 30,
		MoveSpeed = 8,
		DirtHP = 2,
	},
	{
		Id = 30,
		Name = "Toy Plane",
		AssetName = "Toy Plane",
		Rarity = "Uncommon",
		RestorationSteps = { "Spray", "SprayPaint" },
		ChanceWeight = 16,
		Price = 80,
		GuestPay = 8,
		MoveSpeed = 8,
		DirtHP = 1.5,
	},
	{
		Id = 31,
		Name = "Toy Train",
		AssetName = "Toy Train",
		Rarity = "Uncommon",
		RestorationSteps = { "Spray", "Sponge" },
		ChanceWeight = 15,
		Price = 88,
		GuestPay = 10,
		MoveSpeed = 8,
		DirtHP = 1.5,
	},
	{
		Id = 32,
		Name = "Trophy",
		AssetName = "Trophy",
		Rarity = "Epic",
		RestorationSteps = { "SprayPaint", "Sponge" },
		ChanceWeight = 4,
		Price = 290,
		GuestPay = 40,
		MoveSpeed = 8,
		DirtHP = 2.5,
	},
	{
		Id = 33,
		Name = "Vase",
		AssetName = "Vase",
		Rarity = "Rare",
		RestorationSteps = { "Spray", "SprayPaint" },
		ChanceWeight = 7,
		Price = 205,
		GuestPay = 27,
		MoveSpeed = 8,
		DirtHP = 2,
	},
}

return ItemsInfo
