local ItemInteractionConfig = {
	WorldItemDespawnDuration = 60,
	ItemBillboardMaxDistance = 150,
	WorldItemTimerUpdateInterval = 0.1,
	CarryWalkSpeedPenalty = 3,
	DropForwardDistance = 4,
	DroppedItemPurchaseDistance = 10,
	UnexpectedMoveDistance = 8,
	PurchasePriceMultiplier = 1.25,
	MaximumPurchasePriceMultiplier = 3,
	BatKnockbackSpeed = 55,
	BatKnockbackUpwardSpeed = 20,
	MaximumKnockbackSpeed = 70,
	RagdollDuration = 1.1,
	RagdollRecoveryProtectionDuration = 1,
	PvpHitCooldown = 0.8,
	PvpProtectionDuration = 2.5,
	PvpMaximumHitDistance = 10,
	FixingRotationSpeedDegrees = 24,
	SurfacePlacementAttempts = 4,
	SurfacePlacementOffset = 0.015,
	MaximumDirtCount = 160,
}

return ItemInteractionConfig
