type ItemDefinition = {
	Id: number,
	Name: string,
	AssetName: string,
	Rarity: string,
	ChanceWeight: number,
	DifficultyValue: number,
	MoveSpeed: number,
	CarryOffset: CFrame?,
	DirtHP: number,
}

export type ItemInfo = ItemDefinition & {
	Price: number,
	SaleValue: number,
	GuestPay: number,
	RestorationTier: number,
}

local EconomyConfig = require(script.Parent.EconomyConfig)

-- EconomyConfig turns each compact DifficultyValue into the final price and passive income.
local ItemDefinitions: { ItemDefinition } = {
	{
		Id = 1,
		Name = "Wrench",
		AssetName = "Wrench",
		Rarity = "Common",
		ChanceWeight = 34,
		DifficultyValue = 25,
		MoveSpeed = 8,
		DirtHP = 1,
	},
	{
		Id = 2,
		Name = "Knife",
		AssetName = "Knife",
		Rarity = "Uncommon",
		ChanceWeight = 18,
		DifficultyValue = 60,
		MoveSpeed = 8,
		DirtHP = 1.5,
	},
	{
		Id = 3,
		Name = "Hammer",
		AssetName = "Hammer",
		Rarity = "Rare",
		ChanceWeight = 9,
		DifficultyValue = 130,
		MoveSpeed = 8,
		DirtHP = 2,
	},
	{
		Id = 4,
		Name = "Cleaver",
		AssetName = "Cleaver",
		Rarity = "Epic",
		ChanceWeight = 4.5,
		DifficultyValue = 240,
		MoveSpeed = 8,
		DirtHP = 2.5,
	},
	{
		Id = 5,
		Name = "Basketball",
		AssetName = "Basketball",
		Rarity = "Common",
		ChanceWeight = 30,
		DifficultyValue = 35,
		MoveSpeed = 8,
		DirtHP = 1,
	},
	{
		Id = 6,
		Name = "Toaster",
		AssetName = "Toaster",
		Rarity = "Common",
		ChanceWeight = 26,
		DifficultyValue = 45,
		MoveSpeed = 8,
		DirtHP = 1,
	},
	{
		Id = 7,
		Name = "Shovel",
		AssetName = "Shovel",
		Rarity = "Uncommon",
		ChanceWeight = 16,
		DifficultyValue = 75,
		MoveSpeed = 8,
		DirtHP = 1.5,
	},
	{
		Id = 8,
		Name = "Toy Car",
		AssetName = "Toy Car",
		Rarity = "Uncommon",
		ChanceWeight = 14,
		DifficultyValue = 90,
		MoveSpeed = 8,
		DirtHP = 1.5,
	},
	{
		Id = 9,
		Name = "Radio",
		AssetName = "Radio",
		Rarity = "Rare",
		ChanceWeight = 8,
		DifficultyValue = 160,
		MoveSpeed = 8,
		DirtHP = 2,
	},
	{
		Id = 10,
		Name = "Watch",
		AssetName = "Watch",
		Rarity = "Epic",
		ChanceWeight = 4,
		DifficultyValue = 300,
		MoveSpeed = 8,
		DirtHP = 2.5,
	},
	{
		Id = 11,
		Name = "Sword",
		AssetName = "Sword",
		Rarity = "Legendary",
		ChanceWeight = 2.2,
		DifficultyValue = 500,
		MoveSpeed = 8,
		DirtHP = 3,
	},
	{
		Id = 12,
		Name = "Gun",
		AssetName = "Gun",
		Rarity = "Mythic",
		ChanceWeight = 0.9,
		DifficultyValue = 900,
		MoveSpeed = 8,
		DirtHP = 3.5,
	},
	{
		Id = 13,
		Name = "Anchor",
		AssetName = "Anchor",
		Rarity = "Secret",
		ChanceWeight = 0.2,
		DifficultyValue = 1800,
		MoveSpeed = 8,
		DirtHP = 4,
	},
	{
		Id = 14,
		Name = "Alarm Clock",
		AssetName = "Alarm Clock",
		Rarity = "Common",
		ChanceWeight = 30,
		DifficultyValue = 30,
		MoveSpeed = 8,
		DirtHP = 1,
	},
	{
		Id = 15,
		Name = "Binoculars",
		AssetName = "Binoculars",
		Rarity = "Uncommon",
		ChanceWeight = 15,
		DifficultyValue = 85,
		MoveSpeed = 8,
		DirtHP = 1.5,
	},
	{
		Id = 16,
		Name = "Bottle",
		AssetName = "Bottle",
		Rarity = "Common",
		ChanceWeight = 32,
		DifficultyValue = 28,
		MoveSpeed = 8,
		DirtHP = 1,
	},
	{
		Id = 17,
		Name = "Camera",
		AssetName = "Camera",
		Rarity = "Rare",
		ChanceWeight = 8,
		DifficultyValue = 175,
		MoveSpeed = 8,
		DirtHP = 2,
	},
	{
		Id = 18,
		Name = "Desk Fan",
		AssetName = "Desk Fan",
		Rarity = "Common",
		ChanceWeight = 25,
		DifficultyValue = 48,
		MoveSpeed = 8,
		DirtHP = 1,
	},
	{
		Id = 19,
		Name = "Drone",
		AssetName = "Drone",
		Rarity = "Epic",
		ChanceWeight = 3.8,
		DifficultyValue = 325,
		MoveSpeed = 8,
		DirtHP = 2.5,
	},
	{
		Id = 20,
		Name = "Flashlight",
		AssetName = "Flashlight",
		Rarity = "Common",
		ChanceWeight = 28,
		DifficultyValue = 40,
		MoveSpeed = 8,
		DirtHP = 1,
	},
	{
		Id = 21,
		Name = "Gold Bar",
		AssetName = "Gold Bar",
		Rarity = "Legendary",
		ChanceWeight = 1.8,
		DifficultyValue = 650,
		MoveSpeed = 8,
		DirtHP = 3,
	},
	{
		Id = 22,
		Name = "Iron Bar",
		AssetName = "Iron Bar",
		Rarity = "Rare",
		ChanceWeight = 7.5,
		DifficultyValue = 190,
		MoveSpeed = 8,
		DirtHP = 2,
	},
	{
		Id = 23,
		Name = "Magnifying Glass",
		AssetName = "MagnifyingGlass",
		Rarity = "Uncommon",
		ChanceWeight = 17,
		DifficultyValue = 70,
		MoveSpeed = 8,
		DirtHP = 1.5,
	},
	{
		Id = 24,
		Name = "Mango",
		AssetName = "Mango",
		Rarity = "Common",
		ChanceWeight = 31,
		DifficultyValue = 32,
		MoveSpeed = 8,
		DirtHP = 1,
	},
	{
		Id = 25,
		Name = "Medal",
		AssetName = "Medal",
		Rarity = "Rare",
		ChanceWeight = 8.5,
		DifficultyValue = 150,
		MoveSpeed = 8,
		DirtHP = 2,
	},
	{
		Id = 26,
		Name = "Microphone",
		AssetName = "Microphone",
		Rarity = "Uncommon",
		ChanceWeight = 13,
		DifficultyValue = 100,
		MoveSpeed = 8,
		DirtHP = 1.5,
	},
	{
		Id = 27,
		Name = "Old Keyboard",
		AssetName = "Old Keyboard",
		Rarity = "Uncommon",
		ChanceWeight = 14,
		DifficultyValue = 95,
		MoveSpeed = 8,
		DirtHP = 1.5,
	},
	{
		Id = 28,
		Name = "Phone",
		AssetName = "Phone",
		Rarity = "Epic",
		ChanceWeight = 4.2,
		DifficultyValue = 275,
		MoveSpeed = 8,
		DirtHP = 2.5,
	},
	{
		Id = 29,
		Name = "TV",
		AssetName = "TV",
		Rarity = "Rare",
		ChanceWeight = 6.5,
		DifficultyValue = 220,
		MoveSpeed = 8,
		DirtHP = 2,
	},
	{
		Id = 30,
		Name = "Toy Plane",
		AssetName = "Toy Plane",
		Rarity = "Uncommon",
		ChanceWeight = 16,
		DifficultyValue = 80,
		MoveSpeed = 8,
		DirtHP = 1.5,
	},
	{
		Id = 31,
		Name = "Toy Train",
		AssetName = "Toy Train",
		Rarity = "Uncommon",
		ChanceWeight = 15,
		DifficultyValue = 88,
		MoveSpeed = 8,
		DirtHP = 1.5,
	},
	{
		Id = 32,
		Name = "Trophy",
		AssetName = "Trophy",
		Rarity = "Epic",
		ChanceWeight = 4,
		DifficultyValue = 290,
		MoveSpeed = 8,
		DirtHP = 2.5,
	},
	{
		Id = 33,
		Name = "Vase",
		AssetName = "Vase",
		Rarity = "Rare",
		ChanceWeight = 7,
		DifficultyValue = 205,
		MoveSpeed = 8,
		DirtHP = 2,
	},
	{
		Id = 34,
		Name = "Dinosaur Egg",
		AssetName = "Dinosaur Egg",
		Rarity = "Secret",
		ChanceWeight = 0.15,
		DifficultyValue = 2_000,
		MoveSpeed = 8,
		DirtHP = 4,
	},
	{
		Id = 35,
		Name = "Electric Guitar",
		AssetName = "Electric Guitar",
		Rarity = "Epic",
		ChanceWeight = 3.5,
		DifficultyValue = 340,
		MoveSpeed = 8,
		DirtHP = 2.5,
	},
	{
		Id = 36,
		Name = "Fire Hydrant",
		AssetName = "Fire Hydrant",
		Rarity = "Rare",
		ChanceWeight = 7,
		DifficultyValue = 210,
		MoveSpeed = 8,
		DirtHP = 2,
	},
	{
		Id = 37,
		Name = "Gramophone",
		AssetName = "Gramophone",
		Rarity = "Legendary",
		ChanceWeight = 1.7,
		DifficultyValue = 700,
		MoveSpeed = 8,
		DirtHP = 3,
	},
	{
		Id = 38,
		Name = "Grandfather Clock",
		AssetName = "Grandfather Clock",
		Rarity = "Mythic",
		ChanceWeight = 0.7,
		DifficultyValue = 1_100,
		MoveSpeed = 8,
		DirtHP = 3.5,
	},
	{
		Id = 39,
		Name = "Record Player",
		AssetName = "Record Player",
		Rarity = "Rare",
		ChanceWeight = 6.8,
		DifficultyValue = 225,
		MoveSpeed = 8,
		DirtHP = 2,
	},
	{
		Id = 40,
		Name = "Rotary Telephone",
		AssetName = "Rotary Telephone",
		Rarity = "Rare",
		ChanceWeight = 8,
		DifficultyValue = 181,
		MoveSpeed = 8,
		DirtHP = 2,
	},
	{
		Id = 41,
		Name = "Statue",
		AssetName = "Statue",
		Rarity = "Legendary",
		ChanceWeight = 1.5,
		DifficultyValue = 750,
		MoveSpeed = 8,
		DirtHP = 3,
	},
	{
		Id = 42,
		Name = "Telescope",
		AssetName = "Telescope",
		Rarity = "Epic",
		ChanceWeight = 3.6,
		DifficultyValue = 360,
		MoveSpeed = 8,
		DirtHP = 2.5,
	},
	{
		Id = 43,
		Name = "Typewriter",
		AssetName = "Typewriter",
		Rarity = "Epic",
		ChanceWeight = 4.1,
		DifficultyValue = 310,
		MoveSpeed = 8,
		DirtHP = 2.5,
	},
	{
		Id = 44,
		Name = "Washing Machine",
		AssetName = "Washing Machine",
		Rarity = "Uncommon",
		ChanceWeight = 12,
		DifficultyValue = 115,
		MoveSpeed = 8,
		DirtHP = 1.5,
	},
	{
		Id = 45,
		Name = "Moon Rock",
		AssetName = "Moon Rock",
		Rarity = "Legendary",
		ChanceWeight = 1.4,
		DifficultyValue = 780,
		MoveSpeed = 8,
		DirtHP = 3,
	},
	{
		Id = 46,
		Name = "UFO",
		AssetName = "UFO",
		Rarity = "Secret",
		ChanceWeight = 0.1,
		DifficultyValue = 2_400,
		MoveSpeed = 8,
		DirtHP = 4,
	},
	{
		Id = 47,
		Name = "TV Remote",
		AssetName = "Tv remote",
		Rarity = "Common",
		ChanceWeight = 28,
		DifficultyValue = 38,
		MoveSpeed = 8,
		DirtHP = 1,
	},
	{
		Id = 48,
		Name = "Chainsaw",
		AssetName = "Chainsaw",
		Rarity = "Rare",
		ChanceWeight = 7,
		DifficultyValue = 235,
		MoveSpeed = 8,
		DirtHP = 2,
	},
	{
		Id = 49,
		Name = "Rocket",
		AssetName = "Rocket",
		Rarity = "Mythic",
		ChanceWeight = 0.6,
		DifficultyValue = 1_250,
		MoveSpeed = 8,
		DirtHP = 3.5,
	},
	{
		Id = 50,
		Name = "Satellite",
		AssetName = "Satellite",
		Rarity = "Legendary",
		ChanceWeight = 1.3,
		DifficultyValue = 850,
		MoveSpeed = 8,
		DirtHP = 3,
	},
	{
		Id = 51,
		Name = "Speaker",
		AssetName = "Speaker",
		Rarity = "Uncommon",
		ChanceWeight = 13,
		DifficultyValue = 110,
		MoveSpeed = 8,
		DirtHP = 1.5,
	},
	{
		Id = 52,
		Name = "Mammoth Tusk",
		AssetName = "Mammoth Tusk",
		Rarity = "Legendary",
		ChanceWeight = 1.2,
		DifficultyValue = 720,
		MoveSpeed = 8,
		DirtHP = 3,
	},
	{
		Id = 53,
		Name = "Pirate Chest",
		AssetName = "Pirate Chest",
		Rarity = "Epic",
		ChanceWeight = 3.2,
		DifficultyValue = 410,
		MoveSpeed = 8,
		DirtHP = 2.5,
	},
	{
		Id = 54,
		Name = "Fossil",
		AssetName = "Fossil",
		Rarity = "Epic",
		ChanceWeight = 3.4,
		DifficultyValue = 385,
		MoveSpeed = 8,
		DirtHP = 2.5,
	},
	{
		Id = 55,
		Name = "Meteorite",
		AssetName = "Meteorite",
		Rarity = "Mythic",
		ChanceWeight = 0.55,
		DifficultyValue = 1_350,
		MoveSpeed = 8,
		DirtHP = 3.5,
	},
	{
		Id = 56,
		Name = "Motorcycle",
		AssetName = "Motorcycle",
		Rarity = "Epic",
		ChanceWeight = 3.3,
		DifficultyValue = 430,
		MoveSpeed = 8,
		DirtHP = 2.5,
	},
	{
		Id = 57,
		Name = "Safe",
		AssetName = "Safe",
		Rarity = "Epic",
		ChanceWeight = 3.1,
		DifficultyValue = 450,
		MoveSpeed = 8,
		DirtHP = 2.5,
	},
	{
		Id = 58,
		Name = "Air Compressor",
		AssetName = "Air Compressor",
		Rarity = "Rare",
		ChanceWeight = 7.5,
		DifficultyValue = 195,
		MoveSpeed = 8,
		DirtHP = 2,
	},
	{
		Id = 59,
		Name = "Ancient Coin",
		AssetName = "Ancient Coin",
		Rarity = "Legendary",
		ChanceWeight = 1.6,
		DifficultyValue = 740,
		MoveSpeed = 8,
		DirtHP = 3,
	},
	{
		Id = 60,
		Name = "Ancient Idol",
		AssetName = "Ancient Idol",
		Rarity = "Mythic",
		ChanceWeight = 0.65,
		DifficultyValue = 1_180,
		MoveSpeed = 8,
		DirtHP = 3.5,
	},
	{
		Id = 61,
		Name = "Antique Wardrobe",
		AssetName = "Antique Wardrobe",
		Rarity = "Epic",
		ChanceWeight = 3.4,
		DifficultyValue = 390,
		MoveSpeed = 8,
		DirtHP = 2.5,
	},
	{
		Id = 62,
		Name = "Arcade Machine",
		AssetName = "Arcade Machine",
		Rarity = "Epic",
		ChanceWeight = 3.2,
		DifficultyValue = 420,
		MoveSpeed = 8,
		DirtHP = 2.5,
	},
	{
		Id = 63,
		Name = "Astrolabe",
		AssetName = "Astrolabe",
		Rarity = "Legendary",
		ChanceWeight = 1.5,
		DifficultyValue = 770,
		MoveSpeed = 8,
		DirtHP = 3,
	},
	{
		Id = 64,
		Name = "Baseball Bat",
		AssetName = "Baseball Bat",
		Rarity = "Common",
		ChanceWeight = 29,
		DifficultyValue = 36,
		MoveSpeed = 8,
		DirtHP = 1,
	},
	{
		Id = 65,
		Name = "Bench Vise",
		AssetName = "Bench Vise",
		Rarity = "Uncommon",
		ChanceWeight = 14,
		DifficultyValue = 92,
		MoveSpeed = 8,
		DirtHP = 1.5,
	},
	{
		Id = 66,
		Name = "Bicycle",
		AssetName = "Bicycle",
		Rarity = "Rare",
		ChanceWeight = 7.2,
		DifficultyValue = 215,
		MoveSpeed = 8,
		DirtHP = 2,
	},
	{
		Id = 67,
		Name = "Boxing Gloves",
		AssetName = "Boxing Gloves",
		Rarity = "Uncommon",
		ChanceWeight = 15,
		DifficultyValue = 82,
		MoveSpeed = 8,
		DirtHP = 1.5,
	},
	{
		Id = 68,
		Name = "Bulldozer",
		AssetName = "Bulldozer",
		Rarity = "Legendary",
		ChanceWeight = 1.3,
		DifficultyValue = 830,
		MoveSpeed = 8,
		DirtHP = 3,
	},
	{
		Id = 69,
		Name = "Ceiling Fan",
		AssetName = "Ceiling Fan",
		Rarity = "Uncommon",
		ChanceWeight = 13,
		DifficultyValue = 105,
		MoveSpeed = 8,
		DirtHP = 1.5,
	},
	{
		Id = 70,
		Name = "Desk",
		AssetName = "Desk",
		Rarity = "Uncommon",
		ChanceWeight = 12,
		DifficultyValue = 112,
		MoveSpeed = 8,
		DirtHP = 1.5,
	},
	{
		Id = 71,
		Name = "Diving Helmet",
		AssetName = "Diving Helmet",
		Rarity = "Epic",
		ChanceWeight = 3.6,
		DifficultyValue = 365,
		MoveSpeed = 8,
		DirtHP = 2.5,
	},
	{
		Id = 72,
		Name = "Drill Press",
		AssetName = "Drill Press",
		Rarity = "Rare",
		ChanceWeight = 6.8,
		DifficultyValue = 230,
		MoveSpeed = 8,
		DirtHP = 2,
	},
	{
		Id = 73,
		Name = "Factory Machine",
		AssetName = "Factory Machine",
		Rarity = "Mythic",
		ChanceWeight = 0.6,
		DifficultyValue = 1_300,
		MoveSpeed = 8,
		DirtHP = 3.5,
	},
	{
		Id = 74,
		Name = "Forklift",
		AssetName = "Forklift",
		Rarity = "Epic",
		ChanceWeight = 3.1,
		DifficultyValue = 445,
		MoveSpeed = 8,
		DirtHP = 2.5,
	},
	{
		Id = 75,
		Name = "Game Console",
		AssetName = "Game Console",
		Rarity = "Rare",
		ChanceWeight = 8,
		DifficultyValue = 180,
		MoveSpeed = 8,
		DirtHP = 2,
	},
	{
		Id = 76,
		Name = "Garden Fountain",
		AssetName = "Garden Fountain",
		Rarity = "Epic",
		ChanceWeight = 3.5,
		DifficultyValue = 375,
		MoveSpeed = 8,
		DirtHP = 2.5,
	},
	{
		Id = 77,
		Name = "Giant Skull",
		AssetName = "Giant Skull",
		Rarity = "Secret",
		ChanceWeight = 0.14,
		DifficultyValue = 2_150,
		MoveSpeed = 8,
		DirtHP = 4,
	},
	{
		Id = 78,
		Name = "Go-Kart",
		AssetName = "Go-Kart",
		Rarity = "Rare",
		ChanceWeight = 6.7,
		DifficultyValue = 228,
		MoveSpeed = 8,
		DirtHP = 2,
	},
	{
		Id = 79,
		Name = "Grand Piano",
		AssetName = "Grand Piano",
		Rarity = "Mythic",
		ChanceWeight = 0.58,
		DifficultyValue = 1_320,
		MoveSpeed = 8,
		DirtHP = 3.5,
	},
	{
		Id = 80,
		Name = "Harmonica",
		AssetName = "Harmonica",
		Rarity = "Common",
		ChanceWeight = 30,
		DifficultyValue = 34,
		MoveSpeed = 8,
		DirtHP = 1,
	},
	{
		Id = 81,
		Name = "Helicopter",
		AssetName = "Helicopter",
		Rarity = "Mythic",
		ChanceWeight = 0.55,
		DifficultyValue = 1_400,
		MoveSpeed = 8,
		DirtHP = 3.5,
	},
	{
		Id = 82,
		Name = "Lawn Mower",
		AssetName = "Lawn Mower",
		Rarity = "Uncommon",
		ChanceWeight = 12,
		DifficultyValue = 118,
		MoveSpeed = 8,
		DirtHP = 1.5,
	},
	{
		Id = 83,
		Name = "Microscope",
		AssetName = "Microscope",
		Rarity = "Rare",
		ChanceWeight = 7.8,
		DifficultyValue = 185,
		MoveSpeed = 8,
		DirtHP = 2,
	},
	{
		Id = 84,
		Name = "Military Tank",
		AssetName = "Military Tank",
		Rarity = "Secret",
		ChanceWeight = 0.1,
		DifficultyValue = 2_500,
		MoveSpeed = 8,
		DirtHP = 4,
	},
	{
		Id = 85,
		Name = "Oil Barrel",
		AssetName = "Oil Barrel",
		Rarity = "Uncommon",
		ChanceWeight = 13,
		DifficultyValue = 108,
		MoveSpeed = 8,
		DirtHP = 1.5,
	},
	{
		Id = 86,
		Name = "Pinball Machine",
		AssetName = "Pinball Machine",
		Rarity = "Epic",
		ChanceWeight = 3.3,
		DifficultyValue = 405,
		MoveSpeed = 8,
		DirtHP = 2.5,
	},
	{
		Id = 87,
		Name = "RC Car",
		AssetName = "RC Car",
		Rarity = "Uncommon",
		ChanceWeight = 16,
		DifficultyValue = 78,
		MoveSpeed = 8,
		DirtHP = 1.5,
	},
	{
		Id = 88,
		Name = "Rocking Chair",
		AssetName = "Rocking Chair",
		Rarity = "Rare",
		ChanceWeight = 7,
		DifficultyValue = 218,
		MoveSpeed = 8,
		DirtHP = 2,
	},
	{
		Id = 89,
		Name = "Royal Crown",
		AssetName = "Royal Crown",
		Rarity = "Secret",
		ChanceWeight = 0.12,
		DifficultyValue = 2_300,
		MoveSpeed = 8,
		DirtHP = 4,
	},
	{
		Id = 90,
		Name = "Satellite Dish",
		AssetName = "Satellite Dish",
		Rarity = "Epic",
		ChanceWeight = 3.4,
		DifficultyValue = 395,
		MoveSpeed = 8,
		DirtHP = 2.5,
	},
	{
		Id = 91,
		Name = "Shopping Cart",
		AssetName = "Shopping Cart",
		Rarity = "Common",
		ChanceWeight = 25,
		DifficultyValue = 50,
		MoveSpeed = 8,
		DirtHP = 1,
	},
	{
		Id = 92,
		Name = "Steam Engine",
		AssetName = "Steam Engine",
		Rarity = "Legendary",
		ChanceWeight = 1.2,
		DifficultyValue = 880,
		MoveSpeed = 8,
		DirtHP = 3,
	},
	{
		Id = 93,
		Name = "Surfboard",
		AssetName = "Surfboard",
		Rarity = "Uncommon",
		ChanceWeight = 15,
		DifficultyValue = 86,
		MoveSpeed = 8,
		DirtHP = 1.5,
	},
	{
		Id = 94,
		Name = "Teddy Bear",
		AssetName = "Teddy Bear",
		Rarity = "Common",
		ChanceWeight = 27,
		DifficultyValue = 42,
		MoveSpeed = 8,
		DirtHP = 1,
	},
	{
		Id = 95,
		Name = "Toolbox",
		AssetName = "Toolbox",
		Rarity = "Common",
		ChanceWeight = 26,
		DifficultyValue = 46,
		MoveSpeed = 8,
		DirtHP = 1,
	},
	{
		Id = 96,
		Name = "Tractor",
		AssetName = "Tractor",
		Rarity = "Epic",
		ChanceWeight = 3,
		DifficultyValue = 460,
		MoveSpeed = 8,
		DirtHP = 2.5,
	},
	{
		Id = 97,
		Name = "Trumpet",
		AssetName = "Trumpet",
		Rarity = "Rare",
		ChanceWeight = 8.2,
		DifficultyValue = 170,
		MoveSpeed = 8,
		DirtHP = 2,
	},
	{
		Id = 98,
		Name = "VHS Player",
		AssetName = "VHS Player",
		Rarity = "Uncommon",
		ChanceWeight = 14,
		DifficultyValue = 96,
		MoveSpeed = 8,
		DirtHP = 1.5,
	},
	{
		Id = 99,
		Name = "Welding Mask",
		AssetName = "Welding Mask",
		Rarity = "Uncommon",
		ChanceWeight = 13,
		DifficultyValue = 102,
		MoveSpeed = 8,
		DirtHP = 1.5,
	},
	{
		Id = 100,
		Name = "Wheelbarrow",
		AssetName = "Wheelbarrow",
		Rarity = "Common",
		ChanceWeight = 25, 
		DifficultyValue = 52,
		MoveSpeed = 8,
		DirtHP = 1,
	},
}

EconomyConfig.ApplyToItems(ItemDefinitions)
EconomyConfig.ValidateItems(ItemDefinitions)

local ItemsInfo: { ItemInfo } = ItemDefinitions :: any

return ItemsInfo
