local PowerupConfig = {
	RuntimeFolderName = "ClientPowerupDrops",
	Lifetime = 15,
	PickupRadius = 4.5,
	MaximumActive = 48,
	UpdateInterval = 0.08,
	ScatterRadius = NumberRange.new(0.8, 2.2),
	ScatterDuration = NumberRange.new(0.48, 0.68),
	ArcHeight = NumberRange.new(3.8, 5.4),
	VisualHeight = 1.35,

	Bomb = {
		Radius = 28,
		Damage = 600,
		Knockback = 28,
		MaximumTargets = 60,
	},
	Stopwatch = {
		Radius = 52,
		Duration = 5,
		MoveSpeedMultiplier = 0.08,
		MaximumTargets = 80,
	},
	GuardianHalo = {
		Duration = 8,
		MaximumStackedDuration = 16,
	},
	LuckySkull = {
		Duration = 12,
		MaximumStackedDuration = 24,
		RewardMultiplier = 2,
	},

	Order = {
		"CookedChicken",
		"RageCanister",
		"Bomb",
		"ScrapMagnet",
		"Stopwatch",
		"GuardianHalo",
		"LuckySkull",
	},
	Definitions = {
		CookedChicken = {
			DisplayName = "COOKED CHICKEN",
			ActivationText = "FULL HEALTH!",
			ModelName = "CookedChicken",
			Weight = 26,
			Color = Color3.fromRGB(111, 235, 105),
			SoundName = "RegenCoil",
			PulseRadius = 8,
		},
		RageCanister = {
			DisplayName = "RAGE CANISTER",
			ActivationText = "BONUS RAGE!",
			ModelName = "RageCanister",
			Weight = 10,
			Color = Color3.fromRGB(255, 78, 35),
			SoundName = "FlameBurst",
			PulseRadius = 10,
		},
		Bomb = {
			DisplayName = "BOMB",
			ActivationText = "BOOM!",
			ModelName = "Bomb",
			Weight = 16,
			Color = Color3.fromRGB(255, 145, 42),
			SoundName = "FlameBurst",
			PulseRadius = 28,
		},
		ScrapMagnet = {
			DisplayName = "SCRAP MAGNET",
			ActivationText = "ALL DROPS PULLED IN!",
			ModelName = "ScrapMagnet",
			Weight = 18,
			Color = Color3.fromRGB(72, 225, 182),
			SoundName = "MagnetEquip",
			PulseRadius = 18,
		},
		Stopwatch = {
			DisplayName = "STOPWATCH",
			ActivationText = "ZOMBIES SLOWED!",
			ModelName = "Stopwatch",
			Weight = 12,
			Color = Color3.fromRGB(87, 206, 255),
			SoundName = "FreezeRayShoot",
			PulseRadius = 52,
		},
		GuardianHalo = {
			DisplayName = "GUARDIAN HALO",
			ActivationText = "INVULNERABLE!",
			ModelName = "GuardianHalo",
			Weight = 10,
			Color = Color3.fromRGB(255, 226, 94),
			SoundName = "Angellic",
			PulseRadius = 12,
		},
		LuckySkull = {
			DisplayName = "LUCKY SKULL",
			ActivationText = "DOUBLE COINS & XP!",
			ModelName = "LuckySkull",
			Weight = 8,
			Color = Color3.fromRGB(118, 255, 102),
			SoundName = "SlotsJackpot",
			PulseRadius = 12,
		},
	},
}

return table.freeze(PowerupConfig)
