local NODE_SIZE = 96
local HEX_ROW_HEIGHT = math.round(NODE_SIZE * math.sqrt(3) / 2)

local function GetHexPosition(Column: number, Row: number): Vector2
	return Vector2.new(NODE_SIZE * (Column + Row / 2), HEX_ROW_HEIGHT * Row)
end

local UpgradeConfig = {
	NodeSize = NODE_SIZE,
	DefaultZoom = 1.35,
	MinimumZoom = 0.4,
	MaximumZoom = 1.35,
	ZoomStep = 1.14,
	CameraRecoveryDistance = 384,
	MaximumMysteryDistance = 2,
	CameraBounds = Vector2.new(740, 540),
	DefaultDisplayLimit = 8,
	DefaultVisitorsPerDisplay = 2,
	DefaultBatId = "WoodenBat",
	DefaultToolStrengthMultiplier = 1,
	DefaultToolRadiusMultiplier = 1,
	DefaultOwnership = {
		Start = true,
	},
	Upgrades = {
		{
			Id = "Start",
			Name = "Restoration Museum",
			Description = "The beginning of your museum progression.",
			Cost = 0,
			Icon = "Upgrade",
			Position = GetHexPosition(0, 0),
			Prerequisites = {},
			ConnectedUpgrades = { "Display9", "Visitors3", "SpraySpeed1", "UnlockSponge", "StoneBat", "BatCooldown1" },
			Branch = "Core",
			ShortValue = "START",
			Purchasable = false,
		},
		{
			Id = "Display9",
			Name = "9 Displays",
			Description = "Unlocks a ninth usable museum display.",
			Cost = 100,
			Icon = "Area",
			Position = GetHexPosition(1, 0),
			Prerequisites = { "Start" },
			ConnectedUpgrades = { "Display10" },
			Branch = "MuseumCapacity",
			ShortValue = "9 Displays",
			Effect = { Type = "DisplayLimit", Value = 9 },
		},
		{
			Id = "Display10",
			Name = "10 Displays",
			Description = "Unlocks a tenth usable museum display.",
			Cost = 600,
			Icon = "Area",
			Position = GetHexPosition(2, 0),
			Prerequisites = { "Display9" },
			ConnectedUpgrades = { "Display11" },
			Branch = "MuseumCapacity",
			ShortValue = "10 Displays",
			Effect = { Type = "DisplayLimit", Value = 10 },
		},
		{
			Id = "Display11",
			Name = "11 Displays",
			Description = "Unlocks an eleventh usable museum display.",
			Cost = 3_200,
			Icon = "Area",
			Position = GetHexPosition(3, 0),
			Prerequisites = { "Display10" },
			ConnectedUpgrades = { "Display12" },
			Branch = "MuseumCapacity",
			ShortValue = "11 Displays",
			Effect = { Type = "DisplayLimit", Value = 11 },
		},
		{
			Id = "Display12",
			Name = "12 Displays",
			Description = "Unlocks the maximum of twelve museum displays.",
			Cost = 11_000,
			Icon = "Area",
			Position = GetHexPosition(4, 0),
			Prerequisites = { "Display11" },
			ConnectedUpgrades = {},
			Branch = "MuseumCapacity",
			ShortValue = "12 Displays",
			Effect = { Type = "DisplayLimit", Value = 12 },
		},
		{
			Id = "Visitors3",
			Name = "3 Guests",
			Description = "Allows three visitors to inspect one exhibit at once.",
			Cost = 100,
			Icon = "Binoculars",
			Position = GetHexPosition(1, -1),
			Prerequisites = { "Start" },
			ConnectedUpgrades = { "Visitors4" },
			Branch = "MuseumCapacity",
			ShortValue = "3 Guests",
			Effect = { Type = "VisitorsPerDisplay", Value = 3 },
		},
		{
			Id = "Visitors4",
			Name = "4 Guests",
			Description = "Allows four visitors to inspect one exhibit at once.",
			Cost = 900,
			Icon = "Binoculars",
			Position = GetHexPosition(2, -2),
			Prerequisites = { "Visitors3" },
			ConnectedUpgrades = { "Visitors5" },
			Branch = "MuseumCapacity",
			ShortValue = "4 Guests",
			Effect = { Type = "VisitorsPerDisplay", Value = 4 },
		},
		{
			Id = "Visitors5",
			Name = "5 Guests",
			Description = "Allows the maximum of five visitors at one exhibit.",
			Cost = 6_500,
			Icon = "Binoculars",
			Position = GetHexPosition(3, -3),
			Prerequisites = { "Visitors4" },
			ConnectedUpgrades = {},
			Branch = "MuseumCapacity",
			ShortValue = "5 Guests",
			Effect = { Type = "VisitorsPerDisplay", Value = 5 },
		},
		{
			Id = "SpraySpeed1",
			Name = "Spray Speed I",
			Description = "Improves the spray bottle's cleaning speed and radius.",
			Cost = 40,
			Icon = "Auto",
			Position = GetHexPosition(0, 1),
			Prerequisites = { "Start" },
			ConnectedUpgrades = { "SpraySpeed2" },
			Branch = "Restoration",
			ShortValue = "Speed I",
			Effect = { Type = "ToolStrength", ToolId = "Spray", Multiplier = 1.2, RadiusMultiplier = 1.1 },
		},
		{
			Id = "SpraySpeed2",
			Name = "Spray Speed II",
			Description = "Further improves the spray bottle's cleaning speed and radius.",
			Cost = 400,
			Icon = "Auto",
			Position = GetHexPosition(0, 2),
			Prerequisites = { "SpraySpeed1" },
			ConnectedUpgrades = { "SpraySpeed3" },
			Branch = "Restoration",
			ShortValue = "Speed II",
			Effect = { Type = "ToolStrength", ToolId = "Spray", Multiplier = 1.5, RadiusMultiplier = 1.25 },
		},
		{
			Id = "SpraySpeed3",
			Name = "Spray Speed III",
			Description = "Maximizes the spray bottle's cleaning speed and radius.",
			Cost = 3_000,
			Icon = "Auto",
			Position = GetHexPosition(0, 3),
			Prerequisites = { "SpraySpeed2" },
			ConnectedUpgrades = {},
			Branch = "Restoration",
			ShortValue = "Speed III",
			Effect = { Type = "ToolStrength", ToolId = "Spray", Multiplier = 1.9, RadiusMultiplier = 1.4 },
		},
		{
			Id = "UnlockSprayPaint",
			Name = "Unlock Spray Paint",
			Description = "Unlocks spray paint for restoring damaged finishes.",
			Cost = 50,
			Icon = "SprayPaint",
			Position = GetHexPosition(-1, 2),
			Prerequisites = { "UnlockSponge" },
			ConnectedUpgrades = { "SprayPaintSpeed1" },
			Branch = "Restoration",
			ShortValue = "PAINT",
			Effect = { Type = "ToolUnlock", ToolId = "SprayPaint" },
		},
		{
			Id = "SprayPaintSpeed1",
			Name = "Paint Speed I",
			Description = "Improves spray paint restoration speed and radius.",
			Cost = 150,
			Icon = "Auto",
			Position = GetHexPosition(-1, 3),
			Prerequisites = { "UnlockSprayPaint" },
			ConnectedUpgrades = { "SprayPaintSpeed2" },
			Branch = "Restoration",
			ShortValue = "Speed I",
			Effect = { Type = "ToolStrength", ToolId = "SprayPaint", Multiplier = 1.2, RadiusMultiplier = 1.1 },
		},
		{
			Id = "SprayPaintSpeed2",
			Name = "Paint Speed II",
			Description = "Further improves spray paint restoration speed and radius.",
			Cost = 600,
			Icon = "Auto",
			Position = GetHexPosition(-1, 4),
			Prerequisites = { "SprayPaintSpeed1" },
			ConnectedUpgrades = { "SprayPaintSpeed3" },
			Branch = "Restoration",
			ShortValue = "Speed II",
			Effect = { Type = "ToolStrength", ToolId = "SprayPaint", Multiplier = 1.5, RadiusMultiplier = 1.25 },
		},
		{
			Id = "SprayPaintSpeed3",
			Name = "Paint Speed III",
			Description = "Maximizes spray paint restoration speed and radius.",
			Cost = 4_500,
			Icon = "Auto",
			Position = GetHexPosition(-1, 5),
			Prerequisites = { "SprayPaintSpeed2" },
			ConnectedUpgrades = {},
			Branch = "Restoration",
			ShortValue = "Speed III",
			Effect = { Type = "ToolStrength", ToolId = "SprayPaint", Multiplier = 1.9, RadiusMultiplier = 1.4 },
		},
		{
			Id = "UnlockSponge",
			Name = "Unlock Sponge",
			Description = "Unlocks the sponge for scrubbing grease.",
			Cost = 30,
			Icon = "Sponge",
			Position = GetHexPosition(-1, 1),
			Prerequisites = { "Start" },
			ConnectedUpgrades = { "UnlockSprayPaint", "SpongeSpeed1" },
			Branch = "Restoration",
			ShortValue = "SPONGE",
			Effect = { Type = "ToolUnlock", ToolId = "Sponge" },
		},
		{
			Id = "SpongeSpeed1",
			Name = "Sponge Speed I",
			Description = "Improves the sponge's cleaning speed and radius.",
			Cost = 125,
			Icon = "Auto",
			Position = GetHexPosition(-2, 1),
			Prerequisites = { "UnlockSponge" },
			ConnectedUpgrades = { "SpongeSpeed2" },
			Branch = "Restoration",
			ShortValue = "Speed I",
			Effect = { Type = "ToolStrength", ToolId = "Sponge", Multiplier = 1.2, RadiusMultiplier = 1.1 },
		},
		{
			Id = "SpongeSpeed2",
			Name = "Sponge Speed II",
			Description = "Further improves the sponge's cleaning speed and radius.",
			Cost = 500,
			Icon = "Auto",
			Position = GetHexPosition(-3, 1),
			Prerequisites = { "SpongeSpeed1" },
			ConnectedUpgrades = { "SpongeSpeed3" },
			Branch = "Restoration",
			ShortValue = "Speed II",
			Effect = { Type = "ToolStrength", ToolId = "Sponge", Multiplier = 1.5, RadiusMultiplier = 1.25 },
		},
		{
			Id = "SpongeSpeed3",
			Name = "Sponge Speed III",
			Description = "Maximizes the sponge's cleaning speed and radius.",
			Cost = 3_600,
			Icon = "Auto",
			Position = GetHexPosition(-4, 1),
			Prerequisites = { "SpongeSpeed2" },
			ConnectedUpgrades = {},
			Branch = "Restoration",
			ShortValue = "Speed III",
			Effect = { Type = "ToolStrength", ToolId = "Sponge", Multiplier = 1.9, RadiusMultiplier = 1.4 },
		},
		{
			Id = "StoneBat",
			Name = "Stone Bat",
			Description = "A heavier bat with greatly improved crate damage and range.",
			Cost = 150,
			Icon = "StoneBat",
			Position = GetHexPosition(-1, 0),
			Prerequisites = { "Start" },
			ConnectedUpgrades = { "BronzeBat" },
			Branch = "Combat",
			ShortValue = "STONE",
			Effect = { Type = "BatTier", BatId = "StoneBat", Tier = 2 },
		},
		{
			Id = "BronzeBat",
			Name = "Bronze Bat",
			Description = "A sturdy metal bat that breaks tougher crates more efficiently.",
			Cost = 900,
			Icon = "BronzeBat",
			Position = GetHexPosition(-2, 0),
			Prerequisites = { "StoneBat" },
			ConnectedUpgrades = { "GoldBat" },
			Branch = "Combat",
			ShortValue = "BRONZE",
			Effect = { Type = "BatTier", BatId = "BronzeBat", Tier = 3 },
		},
		{
			Id = "GoldBat",
			Name = "Gold Bat",
			Description = "A valuable bat with exceptional crate damage, speed, and range.",
			Cost = 5_000,
			Icon = "GoldBat",
			Position = GetHexPosition(-3, 0),
			Prerequisites = { "BronzeBat" },
			ConnectedUpgrades = { "EmeraldBat" },
			Branch = "Combat",
			ShortValue = "GOLD",
			Effect = { Type = "BatTier", BatId = "GoldBat", Tier = 4 },
		},
		{
			Id = "EmeraldBat",
			Name = "Emerald Bat",
			Description = "A powerful gemstone bat built to crush high-tier crates.",
			Cost = 20_000,
			Icon = "EmeraldBat",
			Position = GetHexPosition(-4, 0),
			Prerequisites = { "GoldBat" },
			ConnectedUpgrades = { "DiamondBat" },
			Branch = "Combat",
			ShortValue = "EMERALD",
			Effect = { Type = "BatTier", BatId = "EmeraldBat", Tier = 5 },
		},
		{
			Id = "DiamondBat",
			Name = "Diamond Bat",
			Description = "An elite bat with immense power against the strongest crates.",
			Cost = 75_000,
			Icon = "DiamondBat",
			Position = GetHexPosition(-5, 0),
			Prerequisites = { "EmeraldBat" },
			ConnectedUpgrades = { "ObsidianBat" },
			Branch = "Combat",
			ShortValue = "DIAMOND",
			Effect = { Type = "BatTier", BatId = "DiamondBat", Tier = 6 },
		},
		{
			Id = "ObsidianBat",
			Name = "Obsidian Bat",
			Description = "The strongest bat, forged to demolish even the rarest crates.",
			Cost = 250_000,
			Icon = "ObsidianBat",
			Position = GetHexPosition(-6, 0),
			Prerequisites = { "DiamondBat" },
			ConnectedUpgrades = {},
			Branch = "Combat",
			ShortValue = "OBSIDIAN",
			Effect = { Type = "BatTier", BatId = "ObsidianBat", Tier = 7 },
		},
		{
			Id = "BatCooldown1",
			Name = "Bat Cooldown I",
			Description = "Improves the attack speed of every bat tier.",
			Cost = 75,
			Icon = "Auto",
			Position = GetHexPosition(0, -1),
			Prerequisites = { "Start" },
			ConnectedUpgrades = { "BatCooldown2" },
			Branch = "CombatSpeed",
			ShortValue = "Level I",
			Effect = { Type = "BatCooldown", Multiplier = 0.9 },
		},
		{
			Id = "BatCooldown2",
			Name = "Bat Cooldown II",
			Description = "Further improves the attack speed of every bat tier.",
			Cost = 900,
			Icon = "Auto",
			Position = GetHexPosition(0, -2),
			Prerequisites = { "BatCooldown1" },
			ConnectedUpgrades = { "BatCooldown3" },
			Branch = "CombatSpeed",
			ShortValue = "Level II",
			Effect = { Type = "BatCooldown", Multiplier = 0.78 },
		},
		{
			Id = "BatCooldown3",
			Name = "Bat Cooldown III",
			Description = "Maximizes the attack speed of every bat tier.",
			Cost = 9_000,
			Icon = "Auto",
			Position = GetHexPosition(0, -3),
			Prerequisites = { "BatCooldown2" },
			ConnectedUpgrades = {},
			Branch = "CombatSpeed",
			ShortValue = "Level III",
			Effect = { Type = "BatCooldown", Multiplier = 0.64 },
		},
	},
}

function UpgradeConfig.Get(UpgradeId: string)
	for _, Upgrade in UpgradeConfig.Upgrades do
		if Upgrade.Id == UpgradeId then return Upgrade end
	end
end

return UpgradeConfig
